config/routes.rb
Rails.application.routes.draw do
  root             'static_pages#home'
  get    'blog'    => 'blog#index'
  get    'login'   => 'sessions#new'
  post   'login'   => 'sessions#create'
  delete 'logout'  => 'sessions#destroy'
  resources :leads, :users, :posts

end

app/views/layouts/_footer.html.erb
<!-- #footer -->
<footer id="footer">

    <!-- .container -->
    <div class="container">

        <p class="copyright-text">&copy; 2016 by <a href="http://www.popcontent.blog.br">PopContent</a><% unless logged_in? %> - <%= link_to "Admin", login_path %> <% end %> </p>

        <ul class="socials social-links circle animated-effect-1">
          <li class="facebook margin-bottom-sm10">
            <a href="https://www.facebook.com/popcontentblog/" title="Facebook"><i class="fa fa-facebook"></i></a>
          </li>
          <li class="instagram margin-bottom-sm10">
            <a href="https://www.instagram.com/popcontent/" title="Instagram"><i class="fa fa-instagram"></i></a>
          </li>
        </ul>
    </div>
    <!-- .container end -->

</footer>
<!-- #footer end -->

app/views/layouts/_header.html.erb
<!-- #header -->
<header id="header">

    <!-- #navigation -->
    <nav id="navigation" class="navbar">

        <!-- .container -->
        <div class="container">

            <div class="navbar-brand">
                <%= link_to root_path do%>
                    <%= image_tag("pop-content-logo.svg", :alt => "Logo") %>
                <% end %>
            </div>

            <ul class="nav navbar-nav">
                <% if params[:controller] == 'static_pages' %>
                    <li class="active"><a href="#header" class="smooth-scroll">Home</a></li>
                    <li><a href="#e-book" class="smooth-scroll">E-book</a></li>
                    <li><a href="#whats-app" class="smooth-scroll">WhatsApp</a></li>
                    <li><a href="#about-us" class="smooth-scroll">O Time</a></li>
                    <li><%= link_to 'Blog', blog_path%></li>
                <% else %>
                    <li><a href="<%= root_path(anchor: 'header' ) %>" class="smooth-scroll">Home</a></li>
                    <li><a href="<%= root_path(anchor: 'e-book' ) %>" class="smooth-scroll">E-book</a></li>
                    <li><a href="<%= root_path(anchor: 'whats-app' ) %>" class="smooth-scroll">WhatsApp</a></li>
                    <li><a href="<%= root_path(anchor: 'about-us' ) %>" class="smooth-scroll">O Time</a></li>
                    <% if params[:controller] == 'blog' or (params[:controller] == 'posts' and params[:action] == 'show')%>
                      <li class="active"> <% else %> <li> <% end %>
                      <%= link_to 'Blog', blog_path%>
                    </li>
                <% end %>
                <% if logged_in? %>
                  <li class="dropdown">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                      Admin
                    </a>
                    <ul class="dropdown-menu">
                      <li><%= link_to "Preferências", edit_user_path(current_user) %></li>
                      <li><%= link_to 'Usuários', users_path %></li>
                      <li><%= link_to "Leads", leads_path %></li>
                      <li><%= link_to "Blog", posts_path %></li>
                      <li class="divider"></li>
                      <li>
                        <%= link_to "Log out", logout_path, method: "delete" %>
                      </li>
                    </ul>
                  </li>
                <% end %>
            </ul>

        </div>
        <!-- .container end -->

    </nav>
    <!-- #navigation end -->

</header>
<!-- #header end -->

app/views/layouts/_modal_signup.html.erb
<div class="modal fade" id='modal-signup'>
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
        <h4 class="modal-title"><i class="fa fa-pencil"></i> Cadastre-se</h4>
        <p>
          Não perca tempo, se cadastre e fale com
          nossos consultores.
        </p>
      </div>
      <div class="modal-body">
        <form id="form-signup-modal" method="post" action="#">
          <div class="submit-status"></div> <!-- submit status -->
            <input type="text" name="lead[name]" id="lead_name" placeholder="Nome Completo" />
            <input type="text" name="lead[email]" id="lead_email" placeholder="E-mail *" />
            <input type="submit" name="submit" value="Cadastrar" class="btn-custom btn-medium" />
            <p class="text-desc"><a href="#">Política de Privacidade</a> &nbsp;-&nbsp; <a href="#">Termos & Condições</a></p>
        </form>
      </div>
    </div><!-- /.modal-content -->
  </div><!-- /.modal-dialog -->
</div><!-- /.modal -->

app/views/layouts/_shev.html.erb
<!--[if lt IE 7]><html class="ie ie6" lang="en"><![endif]-->
<!--[if IE 7]><html class="ie ie7" lang="en"><![endif]-->
<!--[if IE 8]><html class="ie ie8" lang="en"><![endif]-->
<!--[if IE 9]><html class="ie9" lang="en"><![endif]-->
<!--[if (gte IE 10)|!(IE)]><!--><html lang="<%= I18n.locale %>"><!--<![endif]-->

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
  </script>
<![endif]-->


<!--[if lt IE 9]>
  <script src="/assets/html5.js"></script>
  <script src="js/respond.min.js"></script>
<![endif]-->

<!--[if lt IE 8]>
  <link rel="stylesheet" href="css/ie-older.css">
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<%= render 'layouts/shev' %>
<html>
<head>
  <title><%= full_title(yield(:title)) %></title>
  <meta http-equiv="content-type" content="text/html;charset=utf-8" />

  <!-- Google -->
  <% if content_for?(:google_meta) %>
    <%= yield(:google_meta) %>
  <% else%>
    <meta name="description" content="PopContent Marketing Digital" />
    <meta name="keywords" content="market, redes, sociais, publico, alvo, digital,
    empreendedor, empreendedorismo, Whatsapp, inbound, vendas, internet, marketing, lojas,
    aumentar, consultoria, digital, ebook, ecommerce, empresa, inovação, interação, marketing,
    popcontent, sucesso, tecnologia, transformar, vendas, visibilidade" />
    <meta name="author" content="Popcontent" />
    <meta name="application-name" content="Popcontent" />
  <% end %>

  <!-- Facebook -->
  <% if content_for?(:facebook_meta) %>
    <%= yield(:facebook_meta) %>
  <% else%>
    <meta property="og:title" content="PopContent" />
    <meta property="og:url" content="http://popcontent.blog.br/" />
    <meta property="og:image" content="http://popcontent.blog.br/assets/pop-content-logo.svg" />
    <meta property="og:description" content="A PopContent oferece consultoria de marketing para aumentar as vendas da sua empresa e fazer com que ela ganhe mais visibilidade." />
    <meta property="og:site_name" content="PopContent" />
  <% end %>

  <!-- for Twitter -->
  <%= content_for?(:twitter_meta) ? yield(:twitter_meta) : '' %>

  <!-- Mobile Specific Meta -->
  <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">

  <link href="https://fonts.googleapis.com/css?family=Roboto:300,400,700" rel="stylesheet" type="text/css">
  <link href="https://fonts.googleapis.com/css?family=Lato:300,400,700" rel="stylesheet" type="text/css">

  <%= stylesheet_link_tag 'application', params[:controller], media: 'all', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>

  <link rel="shortcut icon" href="/assets/favicon.ico">
  <link rel="apple-touch-icon" href="/assets/apple-touch-icon.png">
  <link rel="apple-touch-icon" sizes="72x72" href="/assets/apple-touch-icon-72x72.png">
  <link rel="apple-touch-icon" sizes="114x114" href="/assets/apple-touch-icon-114x114.png">

  <!-- Facebook Pixel Code -->
  <script>
  !function(f,b,e,v,n,t,s){if(f.fbq)return;n=f.fbq=function(){n.callMethod?
  n.callMethod.apply(n,arguments):n.queue.push(arguments)};if(!f._fbq)f._fbq=n;
  n.push=n;n.loaded=!0;n.version='2.0';n.queue=[];t=b.createElement(e);t.async=!0;
  t.src=v;s=b.getElementsByTagName(e)[0];s.parentNode.insertBefore(t,s)}(window,
  document,'script','https://connect.facebook.net/en_US/fbevents.js');

  fbq('init', '855943844510534');
  fbq('track', "PageView");
  fbq('track', 'Lead');
  fbq('track', 'ViewContent');
  </script>
  <noscript>
    <img height="1" width="1" style="display:none"
    src="https://www.facebook.com/tr?id=855943844510534&ev=PageView&noscript=1"/>
  </noscript>
  <!-- End Facebook Pixel Code -->
</head>
<body>
  <div id="fb-root"></div>
  <script>(function(d, s, id) {
    var js, fjs = d.getElementsByTagName(s)[0];
      if (d.getElementById(id)) return;
      js = d.createElement(s); js.id = id;
      js.src = "//connect.facebook.net/pt_BR/sdk.js#xfbml=1&version=v2.6";
      fjs.parentNode.insertBefore(js, fjs);
    }(document, 'script', 'facebook-jssdk'));
  </script>

  <%= render 'layouts/header' %>
  <%= yield %>
  <%= render 'layouts/footer' %>
  <%= render 'layouts/modal_signup' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-eval' => false %>
  <%= javascript_include_tag params[:controller], 'data-turbolinks-track' => true %>
  <%= debug(params) if Rails.env.development? %>
</script>
</body>
</html>